# Generated by Django 2.2.14 on 2021-10-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=3)),
                ('roll', models.IntegerField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('admissionid', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=20)),
                ('father', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('admissiondate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('teacherid', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
